#name: "mongo-repl-cache"

version: '3'
services:
  # сервер конфигурации
  configSrv:
    image: dh-mirror.gitverse.ru/mongo:latest # docker образ
    container_name: configSrv 
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.10
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",  # запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # 1-й шард 
  shard1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.0.9
    volumes:
      - shard1-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "replSet1", # название реплики
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #реплика 1 шарда 1
  shard1_1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1_1
    restart: always
    ports: 
      - "27022:27022"
    networks:
      app-network:
        ipv4_address: 173.17.0.5
    volumes:
      - shard1_1-data:/data/db
    command: 
      [
        "--shardsvr",
        "--replSet",
        "replSet1",
        "--bind_ip_all",
        "--port",
        "27022"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #реплика 2 шарда 1
  shard1_2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard1_2
    restart: always
    ports: 
      - "27023:27023"
    networks:
      app-network:
        ipv4_address: 173.17.0.4
    volumes:
      - shard1_2-data:/data/db
    command: 
      [
        "--shardsvr",
        "--replSet",
        "replSet1",
        "--bind_ip_all",
        "--port",
        "27023"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # 2-й шард 
  shard2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.0.8
    volumes:
      - shard2-data:/data/db
    command:
      [
        "--shardsvr", # запуск в режиме шардинга
        "--replSet",
        "replSet2", # название реплик
        "--bind_ip_all", # обратите внимание - она отличается от реплики 1-го шарда
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #реплика 1 шарда 2
  shard2_1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2_1
    restart: always
    ports: 
      - "27024:27024"
    networks:
      app-network:
        ipv4_address: 173.17.0.3
    volumes:
      - shard2_1-data:/data/db
    command: 
      [
        "--shardsvr",
        "--replSet",
        "replSet2",
        "--bind_ip_all",
        "--port",
        "27024"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  #реплика 2 шарда 2
  shard2_2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: shard2_2
    restart: always
    ports: 
      - "27025:27025"
    networks:
      app-network:
        ipv4_address: 173.17.0.2
    volumes:
      - shard2_2-data:/data/db
    command: 
      [
        "--shardsvr",
        "--replSet",
        "replSet2",
        "--bind_ip_all",
        "--port",
        "27025"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  # роутер 1
  mongos_router_1:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router_1
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.0.7
    command:
      [
        "mongos", # обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv:27017", # передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s
  
  # роутер 2
  mongos_router_2:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongos_router_2
    restart: always
    ports:
      - "27021:27021"
    networks:
      app-network:
        ipv4_address: 173.17.0.6
    command:
      [
        "mongos", # обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv:27017", # передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27021"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # redis
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379"
    volumes:
      - redis-data:/data
    command: 
      [ 
        "redis-server", 
      ]
    networks:
      app-network:
        ipv4_address: 173.17.0.11

  # # redis 1
  # redis_1:
  #   image: "redis:latest"
  #   container_name: redis_1
  #   ports:
  #     - "6379"
  #   volumes:
  #     - redis_1-data:/data
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   command: 
  #     [ 
  #       "redis-server", 
  #       "/usr/local/etc/redis/redis.conf"
  #     ]
  #   networks:
  #     app-network:
  #       ipv4_address: 173.17.0.11

  # # redis 2
  # redis_2:
  #   image: "redis:latest"
  #   container_name: redis_2
  #   ports:
  #     - "6379"
  #   volumes:
  #     - redis_2-data:/data
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   command: 
  #     [ 
  #       "redis-server", 
  #       "/usr/local/etc/redis/redis.conf" 
  #     ]
  #   networks:
  #     app-network:
  #       ipv4_address: 173.17.0.12

  # # redis 3
  # redis_3:
  #   image: "redis:latest"
  #   container_name: redis_3
  #   ports:
  #     - "6379"
  #   volumes:
  #     - redis_3-data:/data
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   command: 
  #     [ 
  #       "redis-server", 
  #       "/usr/local/etc/redis/redis.conf" 
  #     ]
  #   networks:
  #     app-network:
  #       ipv4_address: 173.17.0.13

  # # redis 4
  # redis_4:
  #   image: "redis:latest"
  #   container_name: redis_4
  #   ports:
  #     - "6379"
  #   volumes:
  #     - redis_4-data:/data
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   command: 
  #     [ 
  #       "redis-server", 
  #       "/usr/local/etc/redis/redis.conf" 
  #     ]
  #   networks:
  #     app-network:
  #       ipv4_address: 173.17.0.14

  # # redis 5
  # redis_5:
  #   image: "redis:latest"
  #   container_name: redis_5
  #   ports:
  #     - "6379"
  #   volumes:
  #     - redis_5-data:/data
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   command: 
  #     [ 
  #       "redis-server", 
  #       "/usr/local/etc/redis/redis.conf" 
  #     ]
  #   networks:
  #     app-network:
  #       ipv4_address: 173.17.0.15

  # # redis 6
  # redis_6:
  #   image: "redis:latest"
  #   container_name: redis_6
  #   ports:
  #     - "6379"
  #   volumes:
  #     - redis_6-data:/data
  #     - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  #   command: 
  #     [ 
  #       "redis-server", 
  #       "/usr/local/etc/redis/redis.conf" 
  #     ]
  #   networks:
  #     app-network:
  #       ipv4_address: 173.17.0.16

  # application
  pymongo_api:
    container_name: mongo-repl-cache
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - configSrv
      - shard1
      - shard1_1
      - shard1_2
      - shard2
      - shard2_1
      - shard2_2
      - mongos_router_1
      - mongos_router_2
      - redis
      # - redis_1
      # - redis_2
      # - redis_3
      # - redis_4
      # - redis_5
      # - redis_6
    ports:
      - 8080:8080
    networks:
      - app-network
    environment:
      #REDIS_URL: "redis://redis:6379"
      #REDIS_URL: "redis://redis_1:6379,redis_2:6379,redis_3:6379,redis_4:6379,redis_5:6379,redis_6:6379"
      MONGODB_URL: "mongodb://mongos_router_1:27020"
      #MONGODB_URL: "mongodb://mongos_router_1:27020,mongos_router_2:27021/?readPreference=secondaryPreferred"
      MONGODB_DATABASE_NAME: "somedb"

networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
  config-data:
  shard1-data:
  shard1_1-data:
  shard1_2-data:
  shard2-data:
  shard2_1-data:
  shard2_2-data:
  redis-data: 
  # redis_1-data:
  # redis_2-data:
  # redis_3-data:
  # redis_4-data:
  # redis_5-data:
  # redis_6-data: